version: "3.9"
services:
  db:
    image: postgis/postgis:16-3.4
    container_name: foodmap-db
    environment:
      POSTGRES_DB: foodmap
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d foodmap"]
      interval: 4s
      timeout: 3s
      retries: 30

  redis:
    image: redis:7
    container_name: foodmap-redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"         
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 4s
      timeout: 3s
      retries: 30

  api:
    build: .
    container_name: foodmap-api
    env_file: .env
    environment:
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data:
