name: CI
on:
  push:
  pull_request:

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Optional: preinstall uv to speed things up (Makefile will work even without this)
      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv

      - name: Install deps
        run: make install

      - name: Compile sources
        run: python -m compileall -q app

