name: CI

on:
  push:
  pull_request:

jobs:
  app-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install fastapi uvicorn sqlalchemy geoalchemy2 psycopg2-binary pydantic passlib[bcrypt] python-jose[cryptography] sqladmin; fi

      # Quick sanity check (no DB, no server start)
      - name: Compile sources
        run: python -m compileall -q app
